### PR TITLE
Added various extra packages (MUI, eCharts etc) and temperature, bushfires and donations charts

### PR DESCRIPTION
**Pull request by mcyph**

### CODE REVIEW

**Review by hqtan — CHANGES_REQUESTED** [review]
this file seems to be empty:
client/src/vis/acorn_weather/RateOfChangeLayer.js 

do we need it?
If it's not needed, can it be removed from the PR?

**Comment by hqtan** [comment]
Hi @mcyph ,

I've just tried deploying the changes in your PR (using the 'Getting Started' instructions from Readme in CfA repo). It failed when I ran `npm start`:
```
$ cd client/

## `npm install` worked fine...
$ npm install
...
added 343 packages from 239 contributors, removed 22 packages, updated 12 packages, moved 4 packages and audited 2208 packages in 20.718s

133 packages are looking for funding
  run `npm fund` for details

found 0 vulnerabilities

$ npm start

> my-webpack-project@1.0.0 start /home/hqtan/mememe/civic-makers/climate-change-project/client
> react-scripts start

Invalid options object. Terser Plugin has been initialized using an options object that does not match the API schema.
 - options has an unknown property 'sourceMap'. These properties are valid:
   object { test?, include?, exclude?, terserOptions?, extractComments?, parallel?, minify? }
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! my-webpack-project@1.0.0 start: `react-scripts start`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the my-webpack-project@1.0.0 start script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/hqtan/.npm/_logs/2020-11-21T09_28_52_382Z-debug.log
```

Are you able to list the set of steps we'd need to take to deploy the app successfully with the changes in your PR?

**Comment by mcyph** [comment]
Thanks for testing - I'm not sure what the problem is to be honest as I can reproduce it locally (on win10 with node v10.15.2), but I think there may have been some extra files added when I executed some webpack-related commands. 

I was doing this to see whether we could add specific handling for `.csv` and other files, but I think this may be more hassle than it's worth as it would require running `npm eject`, or using [craco](https://github.com/gsoft-inc/craco) because of conflicts with `react-scripts`.

Could you please try updating and going `npm install`/`npm start` again? I've reverted most of the `package.json` to how it was before (aside from the new packages which are needed) so hopefully it will be resolved.

**Review by hqtan — APPROVED** [review]

**Comment by hqtan** [comment]
Thx for PR @mcyph ! Awesome work on the charts!
It turns out the issue was possibly due to npm cache issues on my end!
The app ran successfully once I cleared the cache.

**Pull request merged**
